export const useStyles = () => ({
	container: { padding: '20px 10px' },
	formcontrol: { m: 1, minWidth: 120 },
	paper: {
		background: 'white',
		color: 'black',
		padding: '5px 15px',
		borderRadius: '10px',
		cursor: 'pointer',
		// marginTop: '-25px',
		// marginRight: '10px',
	},
	blackpaper: {
		width: '100%',
		textAlign: 'center',
		fontSize: '1rem',
		fontWeight: 500,
		textTransform: 'uppercase',
		fill: '#FFFFFF',
		color: '#FFFFFF',
		backgroundColor: '#00000000',
		borderStyle: 'solid',
		borderWidth: '1px 1px 1px 1px',
		borderRadius: '10px 10px 10px 10px',
		boxShadow: '0px 0px 15px 0px rgb(255 255 255 / 84%)',
		padding: '5px 15px 5px 15px',
		cursor: 'pointer',
	},
});
