import { Stack, Typography } from '@mui/material';
import { Container } from '@mui/system';
import { createClient } from 'contentful';
import React from 'react';
import Footer from 'shared/components/Footer';
import Header from 'shared/components/Header';
import MediaIcons from 'shared/components/MediaIcons';
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import Head from 'next/head';

const client = createClient({ space: 'gaplxiqoo24e', accessToken: 'MHhFPSCj0xiUYWSbBu0m-sI-49msyaJSnc_vWKTGLAE' });

export async function getStaticPaths() {
	const res = await client.getEntries({ content_type: 'blogPost' });

	const paths = res.items.map((item: any) => {
		return { params: { slug: item?.fields?.slug } };
	});
	return {
		paths,
		fallback: true,
	};
}
export async function getStaticProps({ params }: any) {
	const { items } = await client.getEntries({ content_type: 'blogPost', 'fields.slug': params.slug });
	return { props: { news: items[0], params } };
}

const DetailNews = ({ news, params }: any) => {
	return (
		<>
			<Head>
				{/* TODO componentizar los head */}
				<title>{news?.fields?.title} - Landian</title>
				<meta property="og:type" content="website" />
				<meta property="og:title" content={`${news?.fields?.title} - Landian`} />
				<meta
					property="og:description"
					content="WELCOME TO LANDIAN, THE FUTURE OF METAVERSE 1 . 2 Landian Introduction Landian exists so that people, businesses, organizations, and cultures can engage in the Metaverse unencumbered and without limitations.&nbsp;Moreover, it is where becoming anyone or anything is limited only by the imagination. One’s ability to evolve and thrive is determined by level of effort. […]"
				/>
				<meta name="twitter:data1" content="7 minutes" />
				<meta property="og:url" content="https://www.landian.io/" />
				<meta name="twitter:card" content="summary_large_image" />
				<meta property="og:site_name" content="Landian" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/2022/01/logo_black.svg" sizes="32x32" />
			</Head>
			<Header bg="black" />
			<MediaIcons />

			<Container sx={{ pt: { xs: 40, lg: 30 }, pb: 30, flex: 1 }}>
				<Stack spacing={2}>
					<img
						src={news?.fields?.heroImage?.fields?.file?.url}
						width="100%"
						height="400px"
						style={{ objectFit: 'cover' }}
						alt="blog-image"
					/>
					<Typography variant="h4" textAlign="center">
						{news?.fields?.title}
					</Typography>
					<Stack mt={4}>{documentToReactComponents(news?.fields?.content)}</Stack>
				</Stack>
			</Container>
			<Footer />
		</>
	);
};

export default DetailNews;
