import { Typography, Container, Paper, Stack, Divider, Button } from '@mui/material';
import { createClient } from 'contentful';
import Head from 'next/head';
import Link from 'next/link';
import { useTranslation } from 'react-i18next';
import Footer from 'shared/components/Footer';
import Header from 'shared/components/Header';
import MediaIcons from 'shared/components/MediaIcons';

export async function getStaticProps() {
	const client = createClient({ space: 'gaplxiqoo24e', accessToken: 'MHhFPSCj0xiUYWSbBu0m-sI-49msyaJSnc_vWKTGLAE' });
	const res = await client.getEntries({ content_type: 'blogPost' });

	return {
		props: {
			news: res.items,
		},
	};
}

const NewsPage = ({ news }: any) => {
	const { t } = useTranslation();
	return (
		<>
			{' '}
			<Head>
				{/* TODO componentizar los head */}
				<title>News - Landian</title>
				<meta property="og:type" content="website" />
				<meta property="og:title" content="News - Landian" />
				<meta
					property="og:description"
					content="WELCOME TO LANDIAN, THE FUTURE OF METAVERSE 1 . 2 Landian Introduction Landian exists so that people, businesses, organizations, and cultures can engage in the Metaverse unencumbered and without limitations.&nbsp;Moreover, it is where becoming anyone or anything is limited only by the imagination. One’s ability to evolve and thrive is determined by level of effort. […]"
				/>
				<meta name="twitter:data1" content="7 minutes" />
				<meta property="og:url" content="https://www.landian.io/" />
				<meta name="twitter:card" content="summary_large_image" />
				<meta property="og:site_name" content="Landian" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/2022/01/logo_black.svg" sizes="32x32" />
			</Head>
			<Header bg="black" />
			<MediaIcons />
			<Container sx={{ pt: 10, pb: 30, flex: 1 }}>
				<Typography fontWeight="bold" textAlign="center" variant="h4">
					{t('navbar.options.2')}
				</Typography>
				<Stack display="flex" direction="row" flexWrap="wrap" mt={3} gap={5}>
					{news?.map((i: any, index: any) => (
						<Paper key={index} sx={{ background: 'white', color: 'black', width: '354px', height: 620 }}>
							<img src={i.fields.heroImage.fields.file.url} style={{ height: '254px', objectFit: 'cover', width: '100%' }} />
							<Stack p={4}>
								<Typography fontWeight="bold" variant="h6">
									{i?.fields?.title}
								</Typography>
								<Typography paragraph>{i?.fields?.description}</Typography>
								<Stack>
									<Link href={`/news/${i.fields.slug}`}>
										<Button sx={{ color: 'black' }}>Read more</Button>
									</Link>
								</Stack>
								<Divider sx={{ borderColor: '#adadad' }} />
								<Stack
									direction="row"
									justifyContent="space-between"
									alignItems="center"
									spacing={2}
									sx={{ color: '#adadad' }}
									pt={1}>
									<Typography>
										{new Date(i?.fields?.publishDate).toLocaleDateString('en-US', {
											weekday: 'long',
											year: 'numeric',
											month: 'long',
											day: 'numeric',
										})}
									</Typography>

									<Typography>No Comments</Typography>
								</Stack>
							</Stack>
						</Paper>
					))}
				</Stack>
			</Container>
			<Footer />
		</>
	);
};

export default NewsPage;
