import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { useTranslation } from "react-i18next";
import { useEffect } from "react";
import { Button } from "@mui/material";
import Header from "shared/components/Header";
const Home: NextPage = () => {
  const newsContent: any = {
    "en-US": {
      title: "Your News",
      content: [
        {
          title:
            "Otter.ai’s new assistant can automatically transcribe your Zoom meetings",
          synopsis:
            "A.I.-powered voice transcription service Otter.ai wants to make it even easier for its business users to record their meetings. The company is today introducing a new feature, Otter Assistant, whic...",
          imageUrl: "",
        },
        // ...
      ],
    },
    "fr-FR": {
      title: "Vos nouvelles",
      content: [
        {
          title:
            "Le nouvel assistant d'Otter.ai peut transcrire automatiquement vos réunions Zoom",
          synopsis:
            "Le service de transcription vocale alimenté par A.I. Otter.ai veut rendre encore plus facile pour ses utilisateurs professionnels l'enregistrement de leurs réunions. La société présente aujourd'hui une nouvelle fonctionnalité, Otter Assistant, qui ...",
          imageUrl: "",
        },
        // ...
      ],
    },
    "es-ES": {
      title: "Tus noticias",
      content: [
        {
          title:
            "El nuevo asistente de Otter.ai puede transcribir automáticamente sus reuniones de Zoom",
          synopsis:
            "El servicio de transcripción de voz con tecnología de inteligencia artificial Otter.ai quiere facilitar aún más a sus usuarios comerciales la grabación de sus reuniones. La compañía presenta hoy una nueva función, Otter Assistant, que ...",
          imageUrl: "",
        },
        // ...
      ],
    },
  };
  const { locale, locales, defaultLocale, asPath } = useRouter();
  const { t, i18n } = useTranslation();

  console.log(locale, locales, defaultLocale, asPath);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>{t("examples.page.home.head.title")}</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/about">about</Link>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>{locale && newsContent[locale].title}</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
