import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { useTranslation } from 'react-i18next';
import { Box, Typography, Stack, Button, AutocompleteFreeSoloValueMapping } from '@mui/material';
import Header from 'shared/components/Header';
import MediaIcons from 'shared/components/MediaIcons';
import Footer from 'shared/components/Footer';
import Lottie from 'react-lottie';
import animationIntroduction from '../public/2022/03/100801-eyes-intro.json';
import animationTechnology from '../public/2022/03/100739-tec3.json';
import animationEcosystem from '../public/2022/03/100788-builds3.json';
import animationEconomics from '../public/2022/03/101035-layer8.json';
import Imagen from '../public/2022/backgroundSeccion.png';
import background from '../public/2022/backgroundMain.png';
import { Content } from '../shared/components/ReadMore';

const defaultOptionsGlobal = {
	loop: true,
	autoplay: true,
	renderer: 'svg',
};

const Home: NextPage = () => {
	const { t } = useTranslation();
	// ? animation

	const AnimationIntroduction = {
		...defaultOptionsGlobal,
		animationData: animationIntroduction,
	};

	const AnimationTechnology = {
		...defaultOptionsGlobal,
		animationData: animationTechnology,
	};

	const AnimationEcosystem = {
		...defaultOptionsGlobal,
		animationData: animationEcosystem,
	};

	const AnimationEconomics = {
		...defaultOptionsGlobal,
		animationData: animationEconomics,
	};
	return (
		<div className={styles.container}>
			<Head>
				<title>Home - Landian</title>
				<meta property="og:type" content="website" />
				<meta property="og:title" content="Home - Landian" />
				<meta
					property="og:description"
					content="WELCOME TO LANDIAN, THE FUTURE OF METAVERSE 1 . 2 Landian Introduction Landian exists so that people, businesses, organizations, and cultures can engage in the Metaverse unencumbered and without limitations.&nbsp;Moreover, it is where becoming anyone or anything is limited only by the imagination. One’s ability to evolve and thrive is determined by level of effort. […]"
				/>
				<meta name="twitter:data1" content="7 minutes" />
				<meta property="og:url" content="https://www.landian.io/" />
				<meta name="twitter:card" content="summary_large_image" />
				<meta property="og:site_name" content="Landian" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="public/2022/1/logo_black.svg" />
			</Head>
			<Header />
			<MediaIcons />
			<Box
				sx={{
					backgroundImage: `url('${background.src}')`,
					backgroundRepeat: 'no-repeat',
					backgroundSize: '100% 100%',
					backgroundPosition: 'center',
					height: '100vh',
					width: '100vw',
					display: 'flex',
					justifyContent: 'center',
					alignItems: 'center',
				}}>
				<Box sx={{ textAlign: 'center' }}>
					<Typography sx={{ maxWidth: '700px' }} variant="h2">
						{t('homepage.title')}
					</Typography>
				</Box>
			</Box>
			{
				//Introduction
			}
			<Stack
				sx={{
					backgroundImage: `url('${Imagen.src}')`,
					backgroundRepeat: 'no-repeat',
					backgroundSize: '100% 100%',
					backgroundPosition: 'center',
				}}
				display="flex"
				flexDirection="row"
				alignItems="center"
				height={'100vh'}>
				<Box sx={{ marginLeft: '20px', borderBottom: '1px solid  #424949', width: '10.3vw' }}>
					<Typography paragraph sx={{ marginBottom: '0', fontSize: '20px' }}>
						{t('homepage.seccion.1')}
					</Typography>
				</Box>
				<Box marginLeft={'85px'} textAlign="left" px={4} maxWidth={600} top={0}>
					<Typography variant="h3" sx={{ marginBottom: '15px' }}>
						{t('homepage.Introduction.title')}
					</Typography>
					<Content seccion="Introduction" numberWords={496}></Content>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph sx={{ fontWeight: 'bold' }}>
							{t('homepage.seccionLink')}
						</Typography>
						<Box sx={{ display: 'flex', marginTop: '15px' }}>
							<Typography paragraph sx={{ fontWeight: 'lighter', marginRight: '30px' }}>
								{t('homepage.Introduction.relatedLink.0')}
							</Typography>
							<Typography paragraph sx={{ fontWeight: 'lighter' }}>
								{t('homepage.Introduction.relatedLink.1')}
							</Typography>
						</Box>
						<Box sx={{ display: 'flex' }}>
							<Typography paragraph sx={{ fontWeight: 'lighter', marginRight: '30px' }}>
								{t('homepage.Introduction.relatedLink.2')}
							</Typography>
							<Typography paragraph sx={{ fontWeight: 'lighter' }}>
								{t('homepage.Introduction.relatedLink.3')}
							</Typography>
						</Box>
					</Box>
					<Box sx={{ display: 'flex', marginTop: '10px' }}>
						<Typography paragraph sx={{ paddingTop: '5px', marginRight: '20px' }}>
							{t('homepage.information')}
						</Typography>
						<Box>
							<Button variant="dashed">Whitepaper</Button>
						</Box>
					</Box>
				</Box>

				<Box width={700}>
					<Lottie options={AnimationIntroduction} height={500} width={500} />
				</Box>
				<Box sx={{ display: 'flex', alignItems: 'center', marginLeft: '50px' }}>
					<Box sx={{ borderBottom: '1px solid  #424949', width: '10.5vw' }}></Box>
					<Box
						sx={{
							display: 'flex',
							alignItems: 'center',
							justifyContent: 'center',
							width: '50px',
							height: '50px',
							borderRadius: '50%',
							border: '1px solid #C0C0C0',
							opacity: '0.7',
						}}>
						<Typography paragraph sx={{ margin: '0' }}>
							2
						</Typography>
					</Box>
				</Box>
			</Stack>
			{
				//Technology
			}
			<Stack
				sx={{
					backgroundImage: `url('${Imagen.src}')`,
					backgroundRepeat: 'no-repeat',
					backgroundSize: '100% 100%',
					backgroundPosition: 'center',
				}}
				display="flex"
				flexDirection="row"
				alignItems="center"
				height={'100vh'}>
				<Box sx={{ marginLeft: '20px', borderBottom: '1px solid  #424949', width: '10.3vw' }}>
					<Typography paragraph sx={{ marginBottom: '0', fontSize: '20px' }}>
						{t('homepage.seccion.2')}
					</Typography>
				</Box>
				<Box marginLeft={'85px'} textAlign="left" px={4} maxWidth={600} top={0}>
					<Typography variant="h3" sx={{ marginBottom: '15px' }}>
						{t('homepage.Technology.title')}
					</Typography>
					<Content seccion="Technology" numberWords={460}></Content>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph sx={{ fontWeight: 'bold' }}>
							{t('homepage.seccionLink')}
						</Typography>
						<Box sx={{ display: 'flex', marginTop: '15px' }}>
							<Typography paragraph sx={{ fontWeight: 'lighter', marginRight: '30px' }}>
								{t('homepage.Technology.relatedLink.0')}
							</Typography>
							<Typography paragraph sx={{ fontWeight: 'lighter' }}>
								{t('homepage.Technology.relatedLink.1')}
							</Typography>
						</Box>
						<Box sx={{ display: 'flex' }}>
							<Typography paragraph sx={{ fontWeight: 'lighter', marginRight: '30px' }}>
								{t('homepage.Technology.relatedLink.2')}
							</Typography>
							<Typography paragraph sx={{ fontWeight: 'lighter' }}>
								{t('homepage.Technology.relatedLink.3')}
							</Typography>
						</Box>
					</Box>
					<Box sx={{ display: 'flex', marginTop: '10px' }}>
						<Typography paragraph sx={{ paddingTop: '5px', marginRight: '20px' }}>
							{t('homepage.information')}
						</Typography>
						<Box>
							<Button variant="dashed">Whitepaper</Button>
						</Box>
					</Box>
				</Box>

				<Box width={700}>
					<Lottie options={AnimationTechnology} height={500} width={500} />
				</Box>
				<Box sx={{ display: 'flex', alignItems: 'center', marginLeft: '50px' }}>
					<Box sx={{ borderBottom: '1px solid  #424949', width: '10.5vw' }}></Box>
					<Box
						sx={{
							display: 'flex',
							alignItems: 'center',
							justifyContent: 'center',
							width: '50px',
							height: '50px',
							borderRadius: '50%',
							border: '1px solid #C0C0C0',
							opacity: '0.7',
						}}>
						<Typography paragraph sx={{ margin: '0' }}>
							3
						</Typography>
					</Box>
				</Box>
			</Stack>
			{
				//Ecosystem
			}
			<Stack
				sx={{
					backgroundImage: `url('${Imagen.src}')`,
					backgroundRepeat: 'no-repeat',
					backgroundSize: '100% 100%',
					backgroundPosition: 'center',
				}}
				display="flex"
				flexDirection="row"
				alignItems="center"
				height={'100vh'}>
				<Box sx={{ marginLeft: '20px', borderBottom: '1px solid  #424949', width: '10.3vw' }}>
					<Typography paragraph sx={{ marginBottom: '0', fontSize: '20px' }}>
						{t('homepage.seccion.3')}
					</Typography>
				</Box>
				<Box marginLeft={'85px'} textAlign="left" px={4} maxWidth={600} top={0}>
					<Typography variant="h3" sx={{ marginBottom: '15px' }}>
						{t('homepage.Ecosystem.title')}
					</Typography>
					<Content seccion="Ecosystem" numberWords={505}></Content>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph sx={{ fontWeight: 'bold' }}>
							{t('homepage.seccionLink')}
						</Typography>
						<Box sx={{ display: 'flex', marginTop: '15px' }}>
							<Typography paragraph sx={{ fontWeight: 'lighter', marginRight: '30px' }}>
								{t('homepage.Ecosystem.relatedLink.0')}
							</Typography>
							<Typography paragraph sx={{ fontWeight: 'lighter' }}>
								{t('homepage.Ecosystem.relatedLink.1')}
							</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={{ fontWeight: 'lighter', marginRight: '30px' }}>
								{t('homepage.Ecosystem.relatedLink.2')}
							</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={{ fontWeight: 'lighter' }}>
								{t('homepage.Ecosystem.relatedLink.3')}
							</Typography>
						</Box>
					</Box>
					<Box sx={{ display: 'flex', marginTop: '10px' }}>
						<Typography paragraph sx={{ paddingTop: '5px', marginRight: '20px' }}>
							{t('homepage.information')}
						</Typography>
						<Box>
							<Button variant="dashed">Whitepaper</Button>
						</Box>
					</Box>
				</Box>

				<Box width={700}>
					<Lottie options={AnimationEcosystem} height={600} width={600} />
				</Box>
				<Box sx={{ display: 'flex', alignItems: 'center', marginLeft: '50px' }}>
					<Box sx={{ borderBottom: '1px solid  #424949', width: '10.5vw' }}></Box>
					<Box
						sx={{
							display: 'flex',
							alignItems: 'center',
							justifyContent: 'center',
							width: '50px',
							height: '50px',
							borderRadius: '50%',
							border: '1px solid #C0C0C0',
							opacity: '0.7',
						}}>
						<Typography paragraph sx={{ margin: '0' }}>
							4
						</Typography>
					</Box>
				</Box>
			</Stack>
			{
				//Ecosystem
			}
			<Stack
				sx={{
					backgroundImage: `url('${Imagen.src}')`,
					backgroundRepeat: 'no-repeat',
					backgroundSize: '100% 100%',
					backgroundPosition: 'center',
				}}
				display="flex"
				flexDirection="row"
				alignItems="center"
				height={'100vh'}>
				<Box sx={{ marginLeft: '20px', borderBottom: '1px solid  #424949', width: '10.3vw' }}>
					<Typography paragraph sx={{ marginBottom: '0', fontSize: '20px' }}>
						{t('homepage.seccion.4')}
					</Typography>
				</Box>
				<Box marginLeft={'85px'} textAlign="left" px={4} maxWidth={600} top={0}>
					<Typography variant="h3" sx={{ marginBottom: '15px' }}>
						{t('homepage.Economics.title')}
					</Typography>
					<Content seccion="Economics" numberWords={331}></Content>
					<Box sx={{ display: 'flex', marginTop: '10px' }}>
						<Typography paragraph sx={{ paddingTop: '5px', marginRight: '20px' }}>
							{t('homepage.information')}
						</Typography>
						<Box>
							<Button variant="dashed">Whitepaper</Button>
						</Box>
					</Box>
				</Box>

				<Box width={700}>
					<Lottie options={AnimationEconomics} height={600} width={600} />
				</Box>
				<Box sx={{ display: 'flex', alignItems: 'center', marginLeft: '50px' }}>
					<Box sx={{ borderBottom: '1px solid  #424949', width: '10.5vw' }}></Box>
					<Box
						sx={{
							display: 'flex',
							alignItems: 'center',
							justifyContent: 'center',
							width: '50px',
							height: '50px',
							borderRadius: '50%',
							border: '1px solid #C0C0C0',
							opacity: '0.7',
						}}>
						<Typography paragraph sx={{ margin: '0' }}>
							4
						</Typography>
					</Box>
				</Box>
			</Stack>
			<Footer />
		</div>
	);
};

export default Home;
