import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useTranslation } from 'react-i18next';
import { Box, Typography, Stack, Button, TextField, Checkbox, useMediaQuery, Hidden, Paper } from '@mui/material';
import Header from 'shared/components/Header';
import MediaIcons from 'shared/components/MediaIcons';
import Footer from 'shared/components/Footer';
import Lottie from 'react-lottie';
import animationIntroduction from '../public/2022/03/100801-eyes-intro.json';
import animationTechnology from '../public/2022/03/100739-tec3.json';
import animationEcosystem from '../public/2022/03/100788-builds3.json';
import animationEconomics from '../public/2022/03/101035-layer8.json';
import animationConnection from '../public/2022/03/101036-coff3.json';
import animationFuture from '../public/2022/03/100751-occulus.json';
import animationTeam from '../public/2022/03/100741-team-2.json';
import animationLnda from '../public/2022/03/100583-coin.json';
import backgroundSeccion from '../public/2022/backgroundSeccion.png';
import backgroundMain from '../public/2022/backgroundMain.png';
import background from '../public/2022/backgroundMain.png';
import { Content } from '../shared/components/ReadMore';
import { BiShareAlt, BiVector } from 'react-icons/bi';
import { BsFileEarmarkText, BsFillTagFill } from 'react-icons/bs';
import { GiNestedHexagons } from 'react-icons/gi';
import { FaArrowUp, FaTwitter } from 'react-icons/fa';
import { HiDownload } from 'react-icons/hi';
import Image from 'next/image';
import { useStyles } from '../styles/homepage/styled';
import { CheckBox } from '@mui/icons-material';

const defaultOptionsGlobal = {
	loop: true,
	autoplay: true,
	renderer: 'svg',
};

const Home: NextPage = () => {
	const { t } = useTranslation();
	// ? animation

	const medium = useMediaQuery('(max-width:1190px)');
	const small = useMediaQuery('(max-width:899px)');
	const dwarf = useMediaQuery('(max-width:450px)');

	const stylesGeneral = useStyles();

	const AnimationIntroduction = {
		...defaultOptionsGlobal,
		animationData: animationIntroduction,
	};

	const AnimationTechnology = {
		...defaultOptionsGlobal,
		animationData: animationTechnology,
	};

	const AnimationEcosystem = {
		...defaultOptionsGlobal,
		animationData: animationEcosystem,
	};

	const AnimationEconomics = {
		...defaultOptionsGlobal,
		animationData: animationEconomics,
	};
	const AnimationConnection = {
		...defaultOptionsGlobal,
		animationData: animationConnection,
	};
	const AnimationFuture = {
		...defaultOptionsGlobal,
		animationData: animationFuture,
	};
	const AnimationTeam = {
		...defaultOptionsGlobal,
		animationData: animationTeam,
	};

	const AnimationLnda = {
		...defaultOptionsGlobal,
		animationData: animationLnda,
	};
	const classes = {
		input: {
			width: '80%',
			paddingBottom: '10px',
			'& .MuiOutlinedInput-root': {
				background: 'grey',
				borderRadius: '10px 0px 10px 0px',
				'&:hover': {
					cursor: 'pointer',
				},
				'& fieldset': {
					borderRadius: '10px 0px 10px 0px',
				},
			},
		},
	};

	const sizeTeam: number[] = [70, 100, 130];
	return (
		<div className={styles.container}>
			<Head>
				<title>Home - Landian</title>
				<meta property="og:type" content="website" />
				<meta property="og:title" content="Home - Landian" />
				<meta
					property="og:description"
					content="WELCOME TO LANDIAN, THE FUTURE OF METAVERSE 1 . 2 Landian Introduction Landian exists so that people, businesses, organizations, and cultures can engage in the Metaverse unencumbered and without limitations.&nbsp;Moreover, it is where becoming anyone or anything is limited only by the imagination. One’s ability to evolve and thrive is determined by level of effort. […]"
				/>
				<meta name="twitter:data1" content="7 minutes" />
				<meta property="og:url" content="https://www.landian.io/" />
				<meta name="twitter:card" content="summary_large_image" />
				<meta property="og:site_name" content="Landian" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="public/2022/1/logo_black.svg" />
			</Head>

			<Header />

			<MediaIcons />
			<Stack
				sx={{
					backgroundImage: `url('${backgroundMain.src}')`,
					backgroundRepeat: 'no-repeat',
					backgroundSize: '100% 100%',
					backgroundPosition: 'center',
				}}>
				<Box
					sx={{
						height: '100vh',
						width: '100%',
						display: 'flex',
						justifyContent: 'center',
						alignItems: 'center',
					}}>
					<Box sx={{ textAlign: 'center' }}>
						<Typography sx={{ maxWidth: '700px' }} variant="h2">
							{t('homepage.title')}
						</Typography>
					</Box>
				</Box>
			</Stack>

			{
				//Introduction
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								2
							</Typography>
						</Box>
					</Box>
				</Box>

				<Hidden mdDown>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationIntroduction} />
					</Box>
				</Hidden>

				<Box textAlign={{ xs: 'center', md: 'left' }} px={4} top={0} sx={{ alignSelf: 'center' }}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.Introduction.title')}
					</Typography>
					<Content seccion="Introduction" numberWords={507}></Content>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph sx={{ fontWeight: 'bold' }}>
							{t('homepage.seccionLink')}
						</Typography>
						<Box sx={stylesGeneral.seccion.containerRelatedLink}>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.Introduction.relatedLink.0')}
							</Typography>
							<Typography sx={stylesGeneral.seccion.secondRelatedLink}>{t('homepage.Introduction.relatedLink.1')}</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.Introduction.relatedLink.2')}
							</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.secondRelatedLink}>
								{t('homepage.Introduction.relatedLink.3')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerInformation}>
							<Typography paragraph sx={stylesGeneral.seccion.information}>
								{t('homepage.information')}
							</Typography>
							<Box>
								<Button variant="dashed">Whitepaper</Button>
							</Box>
						</Box>
					</Box>
				</Box>
				<Hidden mdUp>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationIntroduction} />
					</Box>
				</Hidden>
				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.1')}
					</Typography>
				</Box>
			</Stack>

			{
				//Technology
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								3
							</Typography>
						</Box>
					</Box>
				</Box>

				<Hidden mdDown>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationTechnology} />
					</Box>
				</Hidden>

				<Box textAlign={{ xs: 'center', md: 'left' }} px={4} top={0} sx={{ alignSelf: 'center' }}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.Technology.title')}
					</Typography>
					<Content seccion="Technology" numberWords={460}></Content>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph sx={{ fontWeight: 'bold' }}>
							{t('homepage.seccionLink')}
						</Typography>
						<Box sx={stylesGeneral.seccion.containerRelatedLink}>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.Technology.relatedLink.0')}
							</Typography>
							<Typography sx={stylesGeneral.seccion.secondRelatedLink}>{t('homepage.Technology.relatedLink.1')}</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.Technology.relatedLink.2')}
							</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.secondRelatedLink}>
								{t('homepage.Technology.relatedLink.3')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerInformation}>
							<Typography paragraph sx={stylesGeneral.seccion.information}>
								{t('homepage.information')}
							</Typography>
							<Box>
								<Button variant="dashed">Whitepaper</Button>
							</Box>
						</Box>
					</Box>
				</Box>
				<Hidden mdUp>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationTechnology} />
					</Box>
				</Hidden>
				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.2')}
					</Typography>
				</Box>
			</Stack>

			{
				//Ecosystem
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								4
							</Typography>
						</Box>
					</Box>
				</Box>

				<Hidden mdDown>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationEcosystem} />
					</Box>
				</Hidden>

				<Box textAlign={{ xs: 'center', md: 'left' }} px={4} top={0} sx={{ alignSelf: 'center' }}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.Ecosystem.title')}
					</Typography>
					<Content seccion="Ecosystem" numberWords={505}></Content>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph sx={{ fontWeight: 'bold' }}>
							{t('homepage.seccionLink')}
						</Typography>
						<Box sx={stylesGeneral.seccion.containerRelatedLink}>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.Ecosystem.relatedLink.0')}
							</Typography>
							<Typography sx={stylesGeneral.seccion.secondRelatedLink}>{t('homepage.Ecosystem.relatedLink.1')}</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.Ecosystem.relatedLink.2')}
							</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.secondRelatedLink}>
								{t('homepage.Ecosystem.relatedLink.3')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerInformation}>
							<Typography paragraph sx={stylesGeneral.seccion.information}>
								{t('homepage.information')}
							</Typography>
							<Box>
								<Button variant="dashed">Whitepaper</Button>
							</Box>
						</Box>
					</Box>
				</Box>
				<Hidden mdUp>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationEcosystem} />
					</Box>
				</Hidden>
				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.3')}
					</Typography>
				</Box>
			</Stack>
			{
				//Economics
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								5
							</Typography>
						</Box>
					</Box>
				</Box>

				<Hidden mdDown>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationEconomics} />
					</Box>
				</Hidden>

				<Box textAlign={{ xs: 'center', md: 'left' }} px={4} top={0} sx={{ alignSelf: 'center' }}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.Economics.title')}
					</Typography>
					<Stack sx={{ opacity: '0.7' }}>
						<Stack sx={stylesGeneral.seccion.containerEconomicsTags}>
							<GiNestedHexagons size={20} />
							<Typography paragraph sx={stylesGeneral.seccion.economicsTagsFirst}>
								{t('homepage.Economics.tags.0')}
							</Typography>
							<BsFileEarmarkText size={20} />
							<Typography paragraph sx={stylesGeneral.seccion.economicsTagsSecond}>
								{t('homepage.Economics.tags.1')}
							</Typography>
						</Stack>
						<Stack sx={stylesGeneral.seccion.containerEconomicsTags}>
							<BiVector size={20} />
							<Typography paragraph sx={stylesGeneral.seccion.economicsTagsFirst}>
								{t('homepage.Economics.tags.2')}
							</Typography>
							<FaArrowUp size={20} />
							<Typography paragraph sx={stylesGeneral.seccion.economicsTagsSecond}>
								{t('homepage.Economics.tags.3')}
							</Typography>
						</Stack>
						<Stack sx={stylesGeneral.seccion.containerEconomicsTags}>
							<BsFillTagFill size={20} />
							<Typography paragraph sx={stylesGeneral.seccion.economicsTagsFirst}>
								{t('homepage.Economics.tags.4')}
							</Typography>
							<BiShareAlt size={20} />
							<Typography paragraph sx={stylesGeneral.seccion.economicsTagsSecond}>
								{t('homepage.Economics.tags.5')}
							</Typography>
						</Stack>
					</Stack>
					<Content seccion="Economics" numberWords={505}></Content>
					<Box sx={{ marginTop: '25px' }}>
						<Box sx={stylesGeneral.seccion.containerInformation}>
							<Typography paragraph sx={stylesGeneral.seccion.information}>
								{t('homepage.information')}
							</Typography>
							<Box>
								<Button variant="dashed">
									Whitepaper
									<HiDownload style={{ paddingLeft: '5px' }} size={17} />
								</Button>
							</Box>
						</Box>
					</Box>
				</Box>
				<Hidden mdUp>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationEconomics} />
					</Box>
				</Hidden>
				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.4')}
					</Typography>
				</Box>
			</Stack>
			{
				//Connection
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								6
							</Typography>
						</Box>
					</Box>
				</Box>

				<Hidden mdDown>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationConnection} />
					</Box>
				</Hidden>

				<Box textAlign={{ xs: 'center', md: 'left' }} px={4} top={0} sx={{ alignSelf: 'center' }}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.Connection.title')}
					</Typography>
					<Content seccion="Connection" numberWords={505}></Content>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph sx={{ fontWeight: 'bold' }}>
							{t('homepage.seccionLink')}
						</Typography>
						<Box sx={stylesGeneral.seccion.containerRelatedLink}>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.Connection.relatedLink.0')}
							</Typography>
							<Typography sx={stylesGeneral.seccion.secondRelatedLink}>{t('homepage.Connection.relatedLink.1')}</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.Connection.relatedLink.2')}
							</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.secondRelatedLink}>
								{t('homepage.Connection.relatedLink.3')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerInformation}>
							<Typography paragraph sx={stylesGeneral.seccion.information}>
								{t('homepage.information')}
							</Typography>
							<Box>
								<Button variant="dashed">Whitepaper</Button>
							</Box>
						</Box>
					</Box>
				</Box>
				<Hidden mdUp>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationConnection} />
					</Box>
				</Hidden>
				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.5')}
					</Typography>
				</Box>
			</Stack>
			{
				//The future
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								7
							</Typography>
						</Box>
					</Box>
				</Box>

				<Hidden mdDown>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationFuture} />
					</Box>
				</Hidden>

				<Box textAlign={{ xs: 'center', md: 'left' }} px={4} top={0} sx={{ alignSelf: 'center' }}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.TheFuture.title')}
					</Typography>
					<Box sx={{ fontSize: { xs: '10.5px', md: '13px', lg: '15px' } }}>
						<pre style={{ textAlign: small ? 'center' : 'left' }}>{t('homepage.TheFuture.description')}</pre>
					</Box>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph sx={{ fontWeight: 'bold' }}>
							{t('homepage.seccionLink')}
						</Typography>
						<Box sx={stylesGeneral.seccion.containerRelatedLink}>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.TheFuture.relatedLink.0')}
							</Typography>
							<Typography sx={stylesGeneral.seccion.secondRelatedLink}>{t('homepage.TheFuture.relatedLink.1')}</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.firstRelatedLink}>
								{t('homepage.TheFuture.relatedLink.2')}
							</Typography>
						</Box>
						<Box>
							<Typography paragraph sx={stylesGeneral.seccion.secondRelatedLink}>
								{t('homepage.TheFuture.relatedLink.3')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerInformation}>
							<Typography paragraph sx={stylesGeneral.seccion.information}>
								{t('homepage.information')}
							</Typography>
							<Box>
								<Button variant="dashed">Whitepaper</Button>
							</Box>
						</Box>
					</Box>
				</Box>
				<Hidden mdUp>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationFuture} />
					</Box>
				</Hidden>
				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.6')}
					</Typography>
				</Box>
			</Stack>
			{
				//Team
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								8
							</Typography>
						</Box>
					</Box>
				</Box>

				<Hidden mdDown>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimationTeam}>
						<Lottie options={AnimationTeam} />
					</Box>
				</Hidden>
				<Box
					textAlign={{ xs: 'center', md: 'left' }}
					px={4}
					top={0}
					sx={{
						alignSelf: 'center',
						flexWrap: 'wrap',
						display: 'flex',
						justifyContent: { xs: 'center', md: 'left', lg: 'left' },
					}}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.Team.title')}
					</Typography>
					<Stack sx={stylesGeneral.seccion.containerMembers}>
						<Box sx={stylesGeneral.seccion.containerTeam}>
							<Box sx={stylesGeneral.seccion.containerImage}>
								<Image
									src="/2022/05/Austin-300x300.jpg"
									layout="responsive"
									width={medium ? 110 : small ? 90 : 130}
									height={medium ? 110 : small ? 90 : 130}
								/>
							</Box>
							<Typography paragraph sx={stylesGeneral.seccion.memberName}>
								{t('homepage.Team.members.0')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerTeam}>
							<Box sx={stylesGeneral.seccion.containerImage}>
								<Image
									src="/2022/05/Alejo-300x300.jpg"
									layout="responsive"
									width={medium ? 110 : small ? 90 : 130}
									height={medium ? 110 : small ? 90 : 130}
								/>
							</Box>
							<Typography paragraph sx={stylesGeneral.seccion.memberName}>
								{t('homepage.Team.members.1')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerTeam}>
							<Box sx={stylesGeneral.seccion.containerImage}>
								<Image
									src="/2022/05/Charlie-300x300.jpg"
									layout="responsive"
									width={medium ? 110 : small ? 90 : 130}
									height={medium ? 110 : small ? 90 : 130}
								/>
							</Box>
							<Typography paragraph sx={stylesGeneral.seccion.memberName}>
								{t('homepage.Team.members.2')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerTeam}>
							<Box sx={stylesGeneral.seccion.containerImage}>
								<Image
									src="/2022/05/Miguel-300x300.jpg"
									layout="responsive"
									width={medium ? 110 : small ? 90 : 130}
									height={medium ? 110 : small ? 90 : 130}
								/>
							</Box>
							<Typography paragraph sx={stylesGeneral.seccion.memberName}>
								{t('homepage.Team.members.3')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerTeam}>
							<Box sx={stylesGeneral.seccion.containerImage}>
								<Image
									src="/2022/05/Omar-300x300.jpg"
									layout="responsive"
									width={medium ? 110 : small ? 90 : 130}
									height={medium ? 110 : small ? 90 : 130}
								/>
							</Box>
							<Typography paragraph sx={stylesGeneral.seccion.memberName}>
								{t('homepage.Team.members.4')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerTeam}>
							<Box sx={stylesGeneral.seccion.containerImage}>
								<Image
									src="/2022/05/Daniel.jpg"
									layout="responsive"
									width={medium ? 110 : small ? 90 : 130}
									height={medium ? 110 : small ? 90 : 130}
								/>
							</Box>
							<Typography paragraph sx={stylesGeneral.seccion.memberName}>
								{t('homepage.Team.members.5')}
							</Typography>
						</Box>
						<Box sx={stylesGeneral.seccion.containerTeam}>
							<Box sx={stylesGeneral.seccion.containerImage}>
								<Image
									src="/2022/05/Elias.jpg"
									layout="responsive"
									width={medium ? 110 : small ? 90 : 130}
									height={medium ? 110 : small ? 90 : 130}
								/>
							</Box>
							<Typography paragraph sx={stylesGeneral.seccion.memberName}>
								{t('homepage.Team.members.6')}
							</Typography>
						</Box>
					</Stack>
					<Box sx={{ marginTop: '25px' }}>
						<Box sx={stylesGeneral.seccion.containerInformation}>
							<Typography paragraph sx={stylesGeneral.seccion.information}>
								{t('homepage.information')}
							</Typography>
							<Box>
								<Button variant="dashed">Whitepaper</Button>
							</Box>
						</Box>
					</Box>
				</Box>
				<Hidden mdUp>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimationTeam}>
						<Lottie options={AnimationTeam} />
					</Box>
				</Hidden>
				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.7')}
					</Typography>
				</Box>
			</Stack>

			{
				//LNDA
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								9
							</Typography>
						</Box>
					</Box>
				</Box>

				<Hidden mdDown>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationLnda} />
					</Box>
				</Hidden>

				<Box textAlign={{ xs: 'center', md: 'left' }} px={4} top={0} sx={{ alignSelf: 'center' }}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.Experience.title')}
					</Typography>
					<Box sx={{ fontSize: { xs: '10px', md: '13px', lg: '15px' } }}>
						<pre style={{ textAlign: small ? 'center' : 'left' }}>{t('homepage.Experience.description')}</pre>
					</Box>
					<Box sx={{ marginTop: '25px' }}>
						<Typography paragraph fontSize={dwarf ? '8px' : ''} sx={{ fontWeight: 'bold' }}>
							{t('homepage.Experience.contract')}
						</Typography>
					</Box>

					<Box sx={stylesGeneral.seccion.containerInformation}>
						<Stack direction={{ xs: 'row', lg: 'row' }} alignItems="center" justifyContent="center" height="100%" gap="5px">
							<Paper sx={stylesGeneral.seccion.paper}>{t('homepage.shortInformation')}</Paper>
							<Paper sx={stylesGeneral.seccion.blackpaper}>swap LNDA</Paper>
						</Stack>
					</Box>
				</Box>
				<Hidden mdUp>
					<Box sx={dwarf ? stylesGeneral.seccion.dwarf : stylesGeneral.seccion.containerAnimation}>
						<Lottie options={AnimationLnda} />
					</Box>
				</Hidden>
				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.8')}
					</Typography>
				</Box>
			</Stack>

			{
				//Suscribe
			}
			<Stack sx={stylesGeneral.seccion.container}>
				<Box sx={stylesGeneral.seccion.separationSeccion}>
					<Box sx={stylesGeneral.seccion.containerNumber}>
						<Box sx={stylesGeneral.seccion.number}>
							<Typography paragraph sx={{ margin: '0' }}>
								10
							</Typography>
						</Box>
					</Box>
				</Box>

				<Box textAlign={'center'} px={4} top={0} sx={{ alignSelf: 'center' }}>
					<Typography variant="h3" sx={stylesGeneral.seccion.titleSeccion}>
						{t('homepage.Suscribe.title')}
					</Typography>
					<Box>
						<Button variant="dashed">
							<FaTwitter size={20} />
							<Typography fontSize={20} sx={{ marginLeft: '10px' }}>
								Twitter
							</Typography>
						</Button>
					</Box>
				</Box>

				<Box sx={stylesGeneral.seccion.nameSeccion}>
					<Typography paragraph sx={stylesGeneral.seccion.textNameSeccion}>
						{t('homepage.seccion.9')}
					</Typography>
				</Box>
			</Stack>
			<Footer />
		</div>
	);
};

export default Home;
