import { Stack, Typography, Box, useMediaQuery } from '@mui/material';
import Head from 'next/head';
import React from 'react';
import Header from 'shared/components/Header';
import Footer from 'shared/components/Footer';
import MediaIcons from 'shared/components/MediaIcons';
import animationCoinData from 'public/2022/03/100583-coin.json';
import Lottie from 'react-lottie';
import { useTranslation } from 'react-i18next';
import Image from 'next/image';
import Link from 'next/link';
import { useStyles } from 'styles/LNDA/styled';

const defaultOptionsGlobal = {
	loop: true,
	autoplay: true,
	renderer: 'svg',
};

const LNDAPage = () => {
	const animationCoin = {
		...defaultOptionsGlobal,
		animationData: animationCoinData,
	};

	const { t } = useTranslation();
	const matches = useMediaQuery('(max-width:930px)');
	const styles = useStyles();
	return (
		<>
			<Head>
				{/* TODO componentizar los head */}
				<title>LNDA token - Landian</title>
				<meta property="og:type" content="website" />
				<meta property="og:title" content="LNDA token - Landian" />
				<meta
					property="og:description"
					content="WELCOME TO LANDIAN, THE FUTURE OF METAVERSE 1 . 2 Landian Introduction Landian exists so that people, businesses, organizations, and cultures can engage in the Metaverse unencumbered and without limitations.&nbsp;Moreover, it is where becoming anyone or anything is limited only by the imagination. One’s ability to evolve and thrive is determined by level of effort. […]"
				/>
				<meta name="twitter:data1" content="7 minutes" />
				<meta property="og:url" content="https://www.landian.io/" />
				<meta name="twitter:card" content="summary_large_image" />
				<meta property="og:site_name" content="Landian" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="public/2022/1/logo_black.svg" />
			</Head>
			<Header bg="black" />
			<MediaIcons />
			<Stack height="100vh" py={[30, 0]} mb={[10, 0]} spacing={2} direction={['column', 'row']} px={[0, 25]} alignItems="center">
				<Stack spacing={2} px={[4, 0]}>
					<Typography variant="h2" fontWeight="bold">
						{t('LNDA.introduction.title')}
					</Typography>
					<Typography paragraph>
						<pre>{t('LNDA.introduction.description')}</pre>
					</Typography>
				</Stack>
				<Stack>
					<Lottie options={animationCoin} height={matches ? 250 : 500} width={matches ? 250 : 500} />
				</Stack>
			</Stack>
			<Stack sx={styles.token.container}>
				<Stack height="100%" sx={styles.token.overlay} justifyContent="center" alignItems="center">
					<Box sx={styles.token.card}>
						<Box sx={styles.token.circle}>
							<Image src="/2022/03/circulo_pequeno.png" width={70} height={70} alt="small-circle" />
						</Box>
						<Box sx={styles.token.group}>
							<Image src="/2022/03/Grupo-13.png" width={110} height={110} alt="group-13" />
						</Box>
						<Typography variant="h4" fontWeight="bold" mb={2}>
							{t('LNDA.tokens.title')}
						</Typography>
						<Stack>
							<Typography>
								<pre>{t('LNDA.tokens.description')}</pre>
							</Typography>
						</Stack>
					</Box>
				</Stack>
			</Stack>
			<Stack sx={styles.circulation.container} justifyContent="center" alignItems="center" direction={['column-reverse', 'row']}>
				<Box>
					<Image src="/2022/03/mano_arriba.png" width={1500} height={487} alt="small-circle" />
				</Box>
				<Stack px={6} spacing={2}>
					<Typography variant="h3" fontWeight="bold">
						{t('LNDA.circulation.title')}
					</Typography>
					<Typography paragraph>
						<pre>{t('LNDA.circulation.description')}</pre>
					</Typography>
					<Link href="/">
						<Typography>{t('LNDA.circulation.link')}</Typography>
					</Link>
				</Stack>
				<Box>
					<Image src="/2022/03/mano_abajo.png" width={1500} height={487} alt="small-circle" />
				</Box>
			</Stack>
			{/* TODO falta la ultima sección */}
			<Footer />
		</>
	);
};

export default LNDAPage;
